<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 *
 * @package    local_acccount
 * @author     Joey Zhang
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

require_once("$CFG->libdir/formslib.php");

class edit extends moodleform {
    // add elements to form
    public function definition()
    {
        global $CFG;

        $mform = $this->_form;

        // 0. acccount id
        $mform->addElement('hidden', 'id');
        $mform->setType('id', PARAM_INT);

        // 1. acccount name
        $mform->addElement('text', 'name', 'Acccount Name');
        $mform->setType('name', PARAM_NOTAGS);
        $mform->setDefault('name', '');

        // 2. acccount site name
        $mform->addElement('text', 'sitename', 'Site Name');
        $mform->setType('sitename', PARAM_NOTAGS);
        $mform->setDefault('sitename', '');


        // 3. acccount site short name
        $mform->addElement('text', 'siteshortname', 'Site Short Name');
        $mform->setType('siteshortname', PARAM_NOTAGS);
        $mform->setDefault('siteshortname', '');

        // 4. acccount id number
        $mform->addElement('text', 'idnumber', 'ID Number');
        $mform->setType('idnumber', PARAM_NOTAGS);
        $mform->setDefault('idnumber', '');


        // add submit and cancel button
        $this->add_action_buttons();
    }

    // custom valication should be added here
    function validation($data, $files)
    {
        return parent::validation($data, $files); // TODO: Change the autogenerated stub
    }
}