<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Version details
 *
 * @package    local_notification
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

require_once("$CFG->libdir/formslib.php");

class editform extends moodleform {
    // add elements to form
    public function definition()
    {
        global $CFG;

        $mform = $this->_form;

        // add notification text input
        $mform->addElement('text', 'notificationtext', 'Notification Text');
        $mform->setType('notificationtext', PARAM_NOTAGS);
        $mform->setDefault('notificationtext', 'Please enter the notification content');


        // add notification type selector
        $options = array();
        $options[\core\output\notification::NOTIFY_SUCCESS] = \core\output\notification::NOTIFY_SUCCESS;
        $options[\core\output\notification::NOTIFY_ERROR] = \core\output\notification::NOTIFY_ERROR;
        $options[\core\output\notification::NOTIFY_INFO] = \core\output\notification::NOTIFY_INFO;
        $options[\core\output\notification::NOTIFY_WARNING] = \core\output\notification::NOTIFY_WARNING;
        $mform->addElement('select', 'notificationtype', 'Notification Type', $options);
        $mform->setDefault('notificationtype', \core\output\notification::NOTIFY_INFO);


        // add submit and cancel button
        $this->add_action_buttons();
    }

    // custom valication should be added here
    function validation($data, $files)
    {
        return parent::validation($data, $files); // TODO: Change the autogenerated stub
    }
}