<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 *
 * @package    local_tenant
 * @author     Joey Zhang
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_tenant;

require_once("$CFG->libdir/formslib.php");

class tenant_edit_form extends \moodleform {

    protected function definition()
    {
        global $CFG;

        $mform = $this->_form;

        // 0. tenant id
        $mform->addElement('hidden', 'tenantid');
        $mform->setType('tenantid', PARAM_INT);

        // 1. tenant name
        $mform->addElement('text', 'tenanttname', 'Tenant Name');
        $mform->setType('tenanttname', PARAM_NOTAGS);
        $mform->setDefault('tenanttname', '');

        // 2. tenant site name
        $mform->addElement('text', 'tenantsitename', 'Site Name');
        $mform->setType('tenantsitename', PARAM_NOTAGS);
        $mform->setDefault('tenantsitename', '');


        // 3. tenant site short name
        $mform->addElement('text', 'tenantsiteshortname', 'Site Short Name');
        $mform->setType('tenantsiteshortname', PARAM_NOTAGS);
        $mform->setDefault('tenantsiteshortname', '');

        // 4. tenant id number
        $mform->addElement('text', 'tenantidnumber', 'ID Number');
        $mform->setType('tenantidnumber', PARAM_NOTAGS);
        $mform->setDefault('tenantidnumber', '');


        // add submit and cancel button
        $this->add_action_buttons();
    }

    // custom validation should be added here
    function validation($data, $files): array
    {
        return parent::validation($data, $files); // TODO: Change the autogenerated stub
    }
}