<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 *
 * @package    local_program
 * @author     Joey Zhang
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

require_once("$CFG->libdir/formslib.php");

class edit extends moodleform {
    // add elements to form
    public function definition()
    {
        global $CFG;

        $data = $this->_customdata['data'];
        $mform = $this->_form;

        // 0. acccount id
        $mform->addElement('hidden', 'programid');
        $mform->setType('programid', PARAM_INT);

        // 1. program name
        $mform->addElement('text', 'programname', 'Program Name');
        $mform->setType('programname', PARAM_NOTAGS);
        $mform->setDefault('programname', '');

        // 2. program short name
        $mform->addElement('text', 'programshortname', 'Program Short Name');
        $mform->setType('programshortname', PARAM_NOTAGS);
        $mform->setDefault('programshortname', '');

        // 3. acccount selector
        $mform->addElement('select', 'programacccount', 'Program Acccount', $this->get_all_acccounts());
        $mform->setType('programacccount', PARAM_NOTAGS);
        $mform->setDefault('programacccount', '');

        // 4. courses list
        $select = $mform->addElement('select', 'programcourses', 'Courses In Program', $this->get_all_courses());
        $select->setMultiple(true);
        $mform->setType('programcourses', PARAM_NOTAGS);
        $mform->setDefault('programcourses', '');

        // add submit and cancel button
        $this->add_action_buttons();
    }

    // custom valication should be added here
    function validation($data, $files)
    {
        return parent::validation($data, $files); // TODO: Change the autogenerated stub
    }

    // TODO: temp function, gonna remove later
    function get_all_acccounts(): array
    {
        global $DB;
        return $DB->get_records_menu('local_acccount', null, '', 'id,name') ?? [];
    }

    function get_all_courses(): array
    {
        global $DB;
        return $DB->get_records_menu('course', null, '', 'id,fullname') ?? [];
    }
}